export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}'
  ],
  theme: {
    extend: {
      extend: {
      colors: {
        "surface-container": "#eaefe7",
        "primary-container": "#0b7a3b",
        "inverse-surface": "#2c322c",
        "secondary-fixed": "#e2e2e2",
        "on-surface": "#181d18",
        "surface-container-high": "#e5eae1",
        "primary-fixed": "#96f8aa",
        tertiary: "#44526b",
        "on-surface-variant": "#3f493f",
        "on-tertiary-fixed-variant": "#39475f",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#dfe4db",
        "on-primary-fixed-variant": "#005225",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#ffffff",
        surface: "#f6fbf2",
        "on-background": "#181d18",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#7adb90",
        "surface-dim": "#d6dcd3",
        "primary-fixed-dim": "#7adb90",
        "on-error-container": "#93000a",
        "on-primary-container": "#a4ffb5",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b9c7e4",
        "surface-container-low": "#f0f5ec",
        outline: "#6f7a6e",
        "on-tertiary-container": "#e2eaff",
        background: "#f6fbf2",
        "tertiary-container": "#5c6a84",
        "on-primary-fixed": "#00210b",
        primary: "#005f2b",
        secondary: "#5d5f5f",
        "on-tertiary-fixed": "#0d1c32",
        "surface-container-highest": "#dfe4db",
        "outline-variant": "#becabc",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-tint": "#006d33",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f6fbf2",
        "on-secondary-fixed-variant": "#454747",
        "inverse-on-surface": "#edf2e9",
        "tertiary-fixed": "#d6e3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      animation: {
        "pulse-sos": "pulse-sos 2s infinite",
        "pulse-red": "pulse-red 2s infinite",
      },
      keyframes: {
        "pulse-sos": {
          "0%": { boxShadow: "0 0 0 0 rgba(220, 38, 38, 0.4)" },
          "70%": { boxShadow: "0 0 0 15px rgba(220, 38, 38, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(220, 38, 38, 0)" },
        },
        "pulse-red": {
          "0%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(220, 38, 38, 0.7)" },
          "70%": { transform: "scale(1)", boxShadow: "0 0 0 10px rgba(220, 38, 38, 0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(220, 38, 38, 0)" },
        },
      },
      boxShadow: {
        card: "0px 4px 20px rgba(10, 25, 47, 0.05)",
        "card-hover": "0px 10px 30px rgba(10, 25, 47, 0.08)",
      },
    },
    },
  },
  plugins: [],
};
